[package]

name = "html5ever"
version = "0.18.0"  # At next breaking change: also remove the "unstable" feature, now a no-op.
authors = [ "The html5ever Project Developers" ]
license = "MIT / Apache-2.0"
repository = "https://github.com/servo/html5ever"
description = "High-performance browser-grade HTML5 parser"
documentation = "https://docs.rs/html5ever"
build = "build.rs"

[lib]
name = "html5ever"

doctest = true

[[test]]
name = "tree_builder"
harness = false

[[test]]
name = "tokenizer"
harness = false

[[test]]
name = "serializer"

[[bench]]
name = "tokenizer"
harness = false

[features]
unstable = []
heap_size = ["markup5ever/heap_size"]

[dependencies]
log = "0.3"
mac = "0.1"
markup5ever = { version = "0.3", path = "../markup5ever" }

[dev-dependencies]
rustc-serialize = "0.3.15"
rustc-test = "0.2"
typed-arena = "1.3.0"

[build-dependencies]
quote = "0.3.3"
syn = { version = "0.11", features = ["full", "visit"] }
